// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLsSDVuMHZEsyHK9q7niDd8eHKl32MMJk',
    appId: '1:717557596367:web:c54aef60dfd7a3ecba77ba',
    messagingSenderId: '717557596367',
    projectId: 'blogapp-7191d',
    authDomain: 'blogapp-7191d.firebaseapp.com',
    databaseURL: 'https://blogapp-7191d-default-rtdb.firebaseio.com',
    storageBucket: 'blogapp-7191d.appspot.com',
    measurementId: 'G-D4MGDPJ8C6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2syaE9295Qh01f9ZFPUuH2hguoBEh8QQ',
    appId: '1:717557596367:android:4c461466a419be7cba77ba',
    messagingSenderId: '717557596367',
    projectId: 'blogapp-7191d',
    databaseURL: 'https://blogapp-7191d-default-rtdb.firebaseio.com',
    storageBucket: 'blogapp-7191d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfGPD1d1P9EtXuvjfYqEtAffxsAHXVK_g',
    appId: '1:717557596367:ios:55ff8017ed01e79bba77ba',
    messagingSenderId: '717557596367',
    projectId: 'blogapp-7191d',
    databaseURL: 'https://blogapp-7191d-default-rtdb.firebaseio.com',
    storageBucket: 'blogapp-7191d.appspot.com',
    androidClientId: '717557596367-cc8ct80pind1bfhudp79a3stgqv2bet9.apps.googleusercontent.com',
    iosClientId: '717557596367-5ihehmtsq38d97r7hhpois1dcj42vbm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfGPD1d1P9EtXuvjfYqEtAffxsAHXVK_g',
    appId: '1:717557596367:ios:c719cd3b3e4e704dba77ba',
    messagingSenderId: '717557596367',
    projectId: 'blogapp-7191d',
    databaseURL: 'https://blogapp-7191d-default-rtdb.firebaseio.com',
    storageBucket: 'blogapp-7191d.appspot.com',
    androidClientId: '717557596367-cc8ct80pind1bfhudp79a3stgqv2bet9.apps.googleusercontent.com',
    iosClientId: '717557596367-6vd5jbvm0irfujp71n0qh5hm5ab7835v.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogApp.RunnerTests',
  );
}
